image: python:3.12-slim

stages:
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest

build:
  stage: build
  script:
    - echo "Build steps"