name: Mirror to GitLab

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - 'app/**'
      - 'models/**'
      - 'scripts/**'
      - '.gitlab-ci.yml'
      - 'requirements.txt'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git config --global user.name "ooibowei"
          git config --global user.email "ooibowei@gmail.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/ooibowei-group/yoga-pose-correction.git
          git push --force gitlab main